- name: curl installation od Debian host
  hosts: all
  become: true

  tasks:
    - name: curl installation only on Debian hosts
      apt:
        name: curl
        state: present
      when: 
        - ansible_os_family == "Debian" 
