- name: install only with dnf packet manager
  hosts: all
  become: true

  tasks:
    - name: install nginx via dnf
      dnf:
        name: nginx
        state: present
      when: ansible_distribution == "Rocky"
