- name: install apache and php on Ubuntu and RedHat hosts
  hosts: all
  become: true

  pre_tasks:

    - name: install updates (Rocky)
      tags: always
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "Rocky"

    - name: install updates (Ubuntu)
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

    - name: apache and php installation on Ubuntu family hosts --> web_servers
      tags: apache,php,ubuntu
      package:
        name: 
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"
  
    - name: apache and php installation on RedHat family hosts --> web_servers
      tags: httpd,php,rocky
      package:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == "Rocky"

- hosts: db_servers
  become: true
  tasks:

    - name: install mariadb on db_servers (Ubuntu)
      tags: mariadb,ubuntu,db
      package:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: install mariadb on db_servers (Rocky)
      tags: mariadb,rocky,db
      package:
        name: mariadb
        state: latest
      when: ansible_distribution == "Rocky"

- hosts: file_servers
  become: true
  tasks:
  
    - name: install samba package
      tags: samba
      package:
        name: samba
        state: latest





# inventory file:
#[web_server]
#root@172.19.0.2 - Rocky
#root@172.19.0.3

#[db_servers]
#root@172.19.0.4

#[file_servers]
#root@172.19.0.5
